### ISSUE TITLE
OS X import Error `.dylib`

### ISSUE THREAD

**Issue by zchee** [nixprime/cpsm#11]
In OS X, it will be build `cpsm_py.dylib` instead `cpsm_py.so` when remove `SUFFIX` flag.
https://github.com/nixprime/cpsm/commit/6e00d1df847a8e75c6d820fc1e3658d1dbbfdc74

but, python can not import `.dylib` file... :(

```
> ls
cpsm.py  cpsm.vim  cpsm_py.dylib*

> python
Python 2.7.10 (default, Oct 31 2015, 01:36:43)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.78)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cpsm_py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named cpsm_py
>>> import cpsm_py.dylib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named cpsm_py.dylib

> mv cpsm_py.dylib cpsm_py.so

> python
Python 2.7.10 (default, Oct 31 2015, 01:36:43)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.78)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cpsm_py
>>> # import success
```

As with python_library, seems necessary osx dedicated flag.

Although there are many problems of OS X, Would you support?

**Comment by zchee** [comment]
Fixed on https://github.com/nixprime/cpsm/pull/12
Close.
